### ISSUE TITLE
create a simple case for heat exchanger with 2 flows

### ISSUE THREAD

**Issue by nagimov** [nagimov/cyclotron-cryopanel#1]
We will need two cases - parallel flow and counter flow.
Then we are going to extend it for 4 flows (nitrogen + helium).
First iteration could have been done without refprop (using constant `cp`) and one-phase flow, so we can use pressure-temperature coordinates system.

**Initial data:**
- flow 1: inlet temperature `T_a_in`, heat capacity `cp_a` (const)
- flow 2: inlet temperature `T_b_in`, heat capacity `cp_b` (const)
- HX: total UA `HX_UA` (const), total length `HX_L`

**Initial conditions**
- flow 1 temperature distribution along HX `T_a = f(x)` (const)
- flow 2 temperature distribution along HX `T_b = g(x)` (const)

**Assumptions:**
- HX's UA is "evenly distributed" along HX's length (i.e. UA of each section is simply `HX_UA / number_of_sections`), i.e. simplified conductance case
- flows have constant `cp`
- no pressure drop (`p_out = p_in`)
- HX's walls have no heat capacity
- no radiation

**Results**
- define the time period of thermal stabilization of HX `T_stab` (outlet temperatures of streams are within `eps_T = 1%` during `eps_t = 10 s`)
- temperature profiles of both streams along HX at `t = 0 s`, `t = T_stab/2`, `t = T_stab`
- temperature dependence of outlets of both stream from `0 s` to `T_stab`

**Comment by nagimov** [comment]
initial revision committed

Result plots:
<img src="https://cloud.githubusercontent.com/assets/3197765/18293495/ee56b7dc-7447-11e6-9efe-57e8886b094a.jpg" width=150px><img src="https://cloud.githubusercontent.com/assets/3197765/18293494/ee55c124-7447-11e6-8c30-16131ea10eaf.png" width=150px><img src="https://cloud.githubusercontent.com/assets/3197765/18293493/ee5382b0-7447-11e6-8d12-8c80f3a1b18e.png" width=150px><img src="https://cloud.githubusercontent.com/assets/3197765/18293496/ee66fdf4-7447-11e6-8623-ec42acffa2eb.png" width=150px>

**Comment by nagimov** [comment]
**TODO:**
- [x] fix variable names according to wiki
- [x] fix calculation logic (densities, surface areas, etc)
- [x] comments through code
- [x] fix long formulations (split to sub-variables)
- [x] simplify case for constant `UA`
- [x] fix result plots according to required results

**Comment by savreline** [comment]
New plots, including new one of temperature vs. length of heat exchanger. 
<img src="https://cloud.githubusercontent.com/assets/21995425/18327588/1f722744-7500-11e6-925f-2b992e46bdbd.png" width=150px><img src="https://cloud.githubusercontent.com/assets/21995425/18327587/1f6fa51e-7500-11e6-9da5-3bf76f5baf00.png" width=150px>

**Comment by savreline** [comment]
To do list is done, code updated on github
ode45 matrix described in the MD file

**Comment by savreline** [comment]
New plots after missing Cp added
<img src="https://cloud.githubusercontent.com/assets/21995425/18328646/9091eee2-7504-11e6-8385-a7896f4484a0.png" width=150px><img src="https://cloud.githubusercontent.com/assets/21995425/18328648/90970dbe-7504-11e6-9c00-22aec4e8d013.png" width=150px>
